* EPFLManager

[[https://travis-ci.org/RomainGehrig/EPFLManager][https://travis-ci.org/RomainGehrig/EPFLManager.svg?branch=master]]

Add commands to ease the day-to-day operations at EPFL

** Installation
To be completed when work on the configuration options is done

(Requires Python 3)

** =site.url= file
A file =site.url= can be put in the directory of a course, enabling the opening of the course site by command line.

A valid file follows this format: each line begins with an url. If it is followed by a space, everything following this space will be considered to be the label of the url. The label is striped of its leading and tailing whitespace to take less visual space.

Example ~Algorithms/site.url~:
#+BEGIN_SRC :raw
http://moodle.epfl.ch/course/view.php?id=13768 Moodle
http://theory.epfl.ch/courses/algorithms/      General site
http://theory.epfl.ch/osven/                   Ola is cool
#+END_SRC

Then ~epfl o alg~ (read: ~epfl open algorithms~) will give:
#+BEGIN_SRC :raw
Possible sites for Algorithms
[1] Moodle       (http://moodle.epfl.ch/course/view.php?id=13768)
[2] General site (http://theory.epfl.ch/courses/algorithms/)
[3] Ola is cool  (http://theory.epfl.ch/osven/)
[q] Quit
Choice:
#+END_SRC

** Configuration file
Configuration file can be found at =~/.config/epflmanager/config.ini=. It consists of three sections: ~version~, ~directories~ and ~moodle~:

~version~: Contains the versions of epflmanager and the configuration reader used to generate the configuration file. Enables migrations of configuration.

~directories~:
- ~main_dir~: the directory containing all the semesters
- ~semester_directories~: names of the directories for every semesters, in chronological order. Used to determine the current semester.
- ~schedule_file~: name of the file in the semester directory that contains the current semester schedule
- ~course_urls_file~: name of the file stored in a course directory which contains the URLs of interest for this course
- ~moodle_config_file~: name of the file containing Moodle informations/config for a particular course

~moodle~:
- ~main_url~: url pointing to the home of Moodle
- ~course_url~: url containing the pattern to access a particular course with its Moodle id
- ~cookie_file~: name of the file that will hold current cookies for the connection the Moodle, in order to allow reconnection if done within a certain span of time (normally 4h)


** Already implemented
- Open the configured URLs of a course
- Separation of the courses by semester
- Display your current schedule
- Create a new course directory
- Run the commands for a previous semester course
- The configuration file is read and used
- Possibility to link a course directory with a Moodle id

** Implementing
- Moodle connection & synchronization
- Init/setup script to install and configure options
