#!/usr/bin/python

import common
import sys

SITE_FILENAME = "site.url"

if __name__ == '__main__':
    s = common.latest_semester()
    course_name = sys.argv[1]
    course = common.handle_ambiguity(s.filter_courses(lambda c: common.fuzzy_match(course_name, c, key=lambda c_: c_.name)))

    if course:
        common.sys_open(course.read_file(SITE_FILENAME))
